automation:
  - alias: Boiler Controller (Hardened)
    mode: restart

    trigger:
      - platform: time_pattern
        minutes: "/2"

    condition:
      - condition: state
        entity_id: input_boolean.boiler_advanced_mode
        state: "on"

    action:
      - variables:
          boiler: climate.hall_thermostat
          standby_temp: 16
          active_temp: 22
          rooms:
            - climate.bathroom_thermostat
            - climate.bedroom_thermostat
            - climate.innes_room_thermostat
            - climate.kitchen_thermostat
            - climate.living_room_thermostat
            - climate.office_thermostat
            
      - choose:
          - conditions: >
              {{ expand(rooms)
                 | selectattr('attributes.hvac_action','defined')
                 | selectattr('attributes.hvac_action','eq','heating')
                 | list
                 | count > 0 }}
            sequence:
              - service: climate.set_temperature
                target:
                  entity_id: "{{ boiler }}"
                data:
                  temperature: "{{ active_temp }}"

              - service: input_text.set_value
                target:
                  entity_id: input_text.boiler_heat_source
                data:
                  value: >
                    {{ expand(rooms)
                       | selectattr('attributes.hvac_action','defined')
                       | selectattr('attributes.hvac_action','eq','heating')
                       | map(attribute='entity_id')
                       | list
                       | first | default('unknown') }}
        default:
          - service: climate.set_temperature
            target:
              entity_id: "{{ boiler }}"
            data:
              temperature: "{{ standby_temp }}"
